### ISSUE TITLE
Todo list for xenial

### ISSUE THREAD

**Issue by nfsprodriver** [ubports/ubuntu-touch#398]
In this thread we want to create a list of things which don't work anymore in xenial (which worked on vivid before). It should be things, which don't need an extra issue each. Please add new problems you explored by leaving a comment. They're going to be added into the following list:

- [x] Filemanager / Terminal etc. don't start in ~ (home directory)

- [x] phone app creates empty white screen, does not start properly
- [x] browser app shows startup splash screen for a second, then closes again
- [x] notes app only brings a white screen
- [x] Ubuntu Store is back 

- [ ] Some apps like Telegram don't have access to their data
  
  - [x] messages app creates empty white screen, does not start properly
 - [ ] camera app tries to start, hangs on splash screen with icon and animated circle
  - [ ] clock app opens, shows clock without pointers for 1 or 2 seconds, then turns into blank white screen
 - [ ] gallery app starts splash screen, then exits again
 - [ ] file manager app starts, then exits again
   - [ ] Open Store broken
 - [x] In system settings the option to add Accounts does not provide a button to add an account. Get only notification that no accounts are set up.
 - [ ] It's not possible to use `phablet-shell` to log into the device: the `ssh` service is not active (must run `sudo service ssh restart` to get it working)

**Comment by Curny** [comment]
**BQ Aquaris E5**:

- In system settings the option to add Accounts does not provide a button to add an account. Get only notification that no accounts are set up.
- Open Store shows categeries and installed apps, but no other apps to install  at all. The screen for the installed apps is also not displaying correctly - here are all apps I had installed in 15.04 but after wiping the device with 16.04 devel they should not be there any more.
- Therefore, Ubuntu Store is back. I tried to install Telegram via Ubuntu Store and here I was asked to log in to my Ubuntu One Account, but this failed with the following error-message: 
> GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.snapcraft.SnapdLoginService was not provided by any .service files

Trying to start all regular apps failed:
- phone app creates empty white screen, does not start properly
- messages app creates empty white screen, does not start properly
- camera app tries to start, hangs on splash screen with icon and animated circle
- browser app shows startup splash screen for a second, then closes again
- clock app opens, shows clock without pointers for 1 or 2 seconds, then turns into blank white screen
- gallery app starts splash screen, then exits again

**Comment by zubozrout** [comment]
@Curny Yup, this is the same for MX4. Though it is interesting the first legacy device release(s) worked better in this respect but many regressions were introduced with the import of changes done on Vivid.

**Comment by BryWilson** [comment]
Meizu Pro 5 (turbo):
I'd like to add: 
In Terminal, style changes have no effect - switch to "Cool retro term" and the terminal remains "black on white".
Using syncevolution to pull in my CardDav Contacts from Nextcloud works a treat - but fails on pulling in CalDav Calendars - appointments show in "Month" view but not in "Day" view.
File Manager won't update in System Updates - downloads but then fails with an error.
Manual installation of click files (using pkcon install-local) fails too.

**Comment by mariogrip** [comment]
dialer fixed: https://github.com/ubports/dialer-app/commit/ec715279dc5e9ec72a9820dea2e83aa1aee64907
messages app: https://github.com/ubports/messaging-app/commit/1d7bd69873714cf8756969d68a3892eaa82a1125
Terminal fixed (new release pushed)
notes app: fixed
browser app: fixed
Ubuntu Store is removed

**Comment by mihaelmilea** [comment]
Pro 5 (turbo): fingerprint unlocking: https://github.com/ubports/ubuntu-touch/issues/396

**Comment by Curny** [comment]
@mariogrip : after downloading the latest updates until today, 07.01.2018, all fixes (dialer, messages, terminal, notes, Store) except the browser work on my E5.
Browser still only brings a white screen and exits again.

**Comment by mihaelmilea** [comment]
@Curny Is there an Updates option in Settings from where you can update to the next daily version of Xenial?

**Comment by mardy** [comment]
I wanted to investigate the Online Accounts issues on my desktop, but for some reason the amd64 ubports repo does not have the ubuntu-system-settings-online-accounts package: it's missing from http://repo.ubports.com/dists/xenial/main/binary-amd64/Packages, while it is in the armhf dist.

@mariogrip , can you do some magic to add it to the amd64 dist as well?

**Comment by dpniel** [comment]
@mardy building now https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubuntu-system-settings-online-accounts/detail/xenial/2/pipeline :-)

**Comment by mardy** [comment]
The Online Accounts panel is working, in the latest image. I removed one item from the list, "Accounts are not handled anymore", because it's not clear what it is about.
Feel free to add it again with more information on how to reproduce the issue.

**Comment by NeoTheThird** [comment]
Tracking multiple issues in one is not practical. Please report separate issues for bugs introduced by xenial. They should include "[xenial]" in the title and be added to the [16.04 Backlog Milestone](https://github.com/ubports/ubuntu-touch/milestone/7).
