### ISSUE TITLE
Tracking issue: Unity 8 in Debian

### ISSUE THREAD

**Issue by tsimonq2** [ubports/ubuntu-touch#819]
We eventually want to upstream all of Unity 8 to Debian and do some of the maintenance there (ideally **all** packaging in [salsa.debian.org](https://salsa.debian.org)).

Here are the blocking issues before this can begin:
 - [ ] #789
 - [ ] #793 
 - [ ] [Get Mir in Debian.](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904305)
 - [ ] Create a dependency graph using something like Graphwiz to map dependencies.
 - [ ] Ensure proper ACLs are set in Salsa for the people who always need access to packaging.

From there:
 1. Ensure packages build against the latest Debian Sid stack.
 1. Full, top-to-bottom Lintian nitpick hackfest.
 1. Move all of the Unity 8 packaging to Salsa, and adjust the CI accordingly.

@sunweaver has offered to sponsor packages, but I'm currently a Debian Maintainer and will start my Debian Developer process immediately after keysigning on the 22nd.

Ideally, @mariogrip and @UniversalSuperBox (or the main people working on Unity 8 on the desktop) should be Debian Maintainers. Once I'm a Debian Developer, we can all keysign, and I'd be happy to work with you to get to the point where I can advocate you for Debian Maintainer. From there I (potentially) won't be needed as much, because uploads would be self-serve.

Once Unity 8 is actively maintained in Debian, we can spin ISOs and apply to be an Ubuntu flavor. I can help with the application to the Ubuntu Technical Board, but we need to appoint points of contact that are specific people.

Let's do this! :+1:
